---
# https://bosh.io/docs/cli-v2.html#deployment-mgmt

name: osb-postgresql

addons:
- name: bpm
  jobs:
  - name: bpm
    release: bpm

releases:
- name: osb-bosh-postgresql
  version: 0+dev.130
- name: bpm
  version: 1.1.8
  url: https://bosh.io/d/github.com/cloudfoundry/bpm-release?v=1.1.8
  sha1: c956394fce7e74f741e4ae8c256b480904ad5942
- name: osb-bosh-haproxy
  version: 0+dev.6
- name: prometheus
  version: latest

update:
  canaries: 1
  max_in_flight: 2
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000

stemcells:
- alias: default
  os: ubuntu-xenial
  version: latest

variables:
- name: transport_ssh
  type: ssh
- name: pcp_password
  type: password
- name: service_credentials
  type: user
  options:
    username: service
- name: backup_credentials
  type: user
  options:
    username: backup
- name: exporter_credentials
  type: user
  options:
    username: exporter
- name: replicationPassword
  type: password
- name: ssl_ca
  type: certificate
  options:
    is_ca: true
    common_name: postgres-ssl

instance_groups:
- name: postgres
  instances: 2
  vm_type: small
  stemcell: default
  azs:
  - z1
  networks:
  - name: service
  persistent_disk_type: 10GB
  consumes:
    zookeeper:
      deployment: osb-zookeeper
  consumes:
    haproxy: {}
  jobs:
  - name: postgres
    release: osb-bosh-postgresql
  - name: backup-agent
    release: osb-bosh-postgresql
  - name: postgres_exporter
    release: prometheus
    properties:
  properties:
    patroni:
      zookeeper:
        enabled: true
    postgres_exporter:
      datasource_name: "postgresql://((exporter_credentials.username)):((exporter_credentials.password))@localhost:5432/postgres?sslmode=verify-full"
    backup_agent:
      username: ((backup_credentials.username))
      password: ((backup_credentials.password))
    postgres:
      ssl:
        enabled: true
        ca: ((ssl_ca.certificate))((ssl_ca.ca))
        cakey: ((ssl_ca.private_key))
      resource:
        shared_buffers: 128MB
        temp_buffers: 8MB
      encoding:
        lc_messages: 'en_US.UTF-8'
        lc_monetary: 'en_US.UTF-8'
        lc_numeric:  'en_US.UTF-8'
        lc_time:     'en_US.UTF-8'
      config:
        port: 5432
        max_connections: 400
        max_files_per_process: 1000
        shared_preload_libraries: 'pg_stat_statements'
      archive_cleanup:
        threshold: 10
      hba:
        - host all all 0.0.0.0/0 md5
        - host all all ::/0 md5
      replication:
        archive_mode: 'on'
        enabled: true
        password: ((replicationPassword))
      admin_users:
      - username: ((service_credentials.username))
        password: ((service_credentials.password))
        admin: true
      - username: ((exporter_credentials.username))
        password: ((exporter_credentials.password))
        admin: false
      backup_users:
      - username: ((backup_credentials.username))
        password: ((backup_credentials.password))
      users:
      - username: pgpool_health
        password: ((service_credentials.password))
        admin: true
      databases:
      - name: admin
        users:
        - pgpool_health
        - ((service_credentials.username))
        extensions: 
        - citext 
#      - name: pgpool_health
#        users:
#        - pgpool_health
#        extensions: 
#        - citext 
#      - name: admin
#        users:
#        - ((service_credentials.username))
#        extensions: 
#        - citext 

- name: haproxy
  azs: [z1]
  instances: 1
  vm_type: default
  stemcell: default
  networks: [{name: default}]
  jobs:
  - name: haproxy
    release: osb-bosh-haproxy
    custom_provider_definitions:
    - name: haproxy
      type: haproxy
    provides:
      haproxy: {}
    consumes:
      tcp_backend: {}
    properties:
      ha_proxy:
        max_connections: 100
        client_timeout:  1800
        connect_timeout: 4
        server_timeout: 1800
        backend_port: 5432
        check_timeout: 5
        tcp_link_port: 5432
        tcp_link_check_port: 8008
        tcp_backend_config: |
          option httpchk
          http-check expect status 200
          default-server inter 3s fall 3 rise 2 on-marked-down shutdown-sessions
- name: pg-bench-and-backup-smoke-tests
  instances: 1
  stemcell: default
  vm_type: minimal
  lifecycle: errand
  azs:
  - z1
  networks:
  - name: default
  persistent_disk: 0
  jobs:
  - name: smoke-tests
    release: osb-bosh-postgresql
    properties:
      smoke_tests:
        backend:
          port: 5432
        target:
          username: ((service_credentials.username))
          password: ((service_credentials.password))
          port: 5432
